version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: appcontainer
    tty: true
    restart: always
    volumes:
      - ./ssh:/home/user/.ssh
#    command: chmod -R 700 /home/user/.ssh
